# Throwable

# Error
- 错误： 错误不是异常，而是脱离程序员控制的问题。错误在代码中通常被忽略。例如，当栈溢出时，一个错误就发生了，它们在编译也检查不到的。
- OutOfMemoryError、StackOverflowError等都是VirtualMachineError 虚拟机错误

# Exception
- 在 Java 内置类中(接下来会说明)，有大部分常用检查性和非检查性异常。

- 运行时异常和非运行时异常
    - 运行时抛出的异常 如IndexOutOfBoundsException、NullPointerException 继承了RuntimeException的这种常见的运行时异常，
    只有在程序运行时才可能会[抛出的异常
    - 非运行时异常（检查性异常）：如IOException 会在编译期检查有可能抛出的异常而做出处理


# try-with-resources
- JDK7 之后，Java 新增的 try-with-resource 语法糖来打开资源，并且可以在语句执行完毕后确保每个资源都被自动关闭 。
- JDK7 之前所有被打开的系统资源，比如流、文件或者 Socket 连接等，都需要被开发者手动关闭，否则将会造成资源泄露。

```
try (resource declaration) {
  // 使用的资源
} catch (ExceptionType e1) {
  // 异常块
}
```

以上的语法中 try 用于声明和实例化资源，catch 用于处理关闭资源时可能引发的所有异常。

注意：try-with-resources 语句关闭所有实现 AutoCloseable 接口的资源。

## try-with-resources 处理多个资源
- try-with-resources 语句中可以声明多个资源，方法是使用分号 ; 分隔各个资源：

